### ISSUE TITLE
COAP throws exception when running under Python 3.9

### ISSUE THREAD

**Issue by johtso** [rgerganov/py-air-control#69]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/human/.local/pipx/venvs/py-air-control/lib/python3.9/site-packages/coapthon/client/coap.py", line 270, in receive_datagram
    self._send_ack(transaction)
  File "/Users/human/.local/pipx/venvs/py-air-control/lib/python3.9/site-packages/coapthon/client/coap.py", line 304, in _send_ack
    self.send_datagram(ack)
  File "/Users/human/.local/pipx/venvs/py-air-control/lib/python3.9/site-packages/coapthon/client/coap.py", line 168, in send_datagram
    if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

Doesn't look like CoAPthon3 is actively maintained, so maybe just a warning on the readme?

**Comment by rgerganov** [comment]
Thanks for reporting this, it is yet another problem with the CoAPthon3 library ... I am thinking to create a fork of this library where I can fix stuff like this and suggest people to update from the fork in the README.

**Comment by CatalinMustata** [comment]
I've installed this on a new system and got Python 3.9 by default. Did use your fork of CoAPthon3, as I understood this works with 3.9 as well, but no luck. 

What's the current status?
